server:
  port: 9000

logging:
  level:
    org.springframework.security: ${LOGGING_LEVEL:INFO}

spring:
  application:
    name: multi-tenant-salon-authz
    identity-service-url: ${IDENTITY_SERVICE_URL:http://localhost:8080}
    cors-allowed-origin-pattern: ${CORS_ALLOWED_ORIGIN_PATTERN:*}
    mailjet:
      sender: "noreply@salonsaas.org"
      api-key: ${MAILJET_API_KEY:asfa}
      api-secret: ${MAILJET_API_SECRET:sfas}
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
          public-client:
            registration:
              client-id: "public-client"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:3000"
                - "http://localhost:3000"
              scopes:
                - "openid"
                - "profile"
            token:
              access-token-time-to-live: 30m
          salon-admin:
            registration:
              client-id: "salon-admin"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris:
                - "https://admin.salonsaas.org/login"
              post-logout-redirect-uris:
                - "https://admin.salonsaas.org/login"
              scopes:
                - "openid"
                - "profile"
            token:
              access-token-time-to-live: 30m
          salon-super-admin:
            registration:
              client-id: "salon-super-admin"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris:
                - "https://super-admin.salonsaas.org/login"
              post-logout-redirect-uris:
                - "https://super-admin.salonsaas.org/login"
              scopes:
                - "openid"
                - "profile"
            token:
              access-token-time-to-live: 30m
          salon-staff:
            registration:
              client-id: "salon-staff"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris:
                - "https://staff.salonsaas.org/login"
              post-logout-redirect-uris:
                - "https://staff.salonsaas.org/login"
              scopes:
                - "openid"
                - "profile"
            token:
              access-token-time-to-live: 30m
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
